# Generated by Django 2.1.7 on 2019-11-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaveapply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_session', models.CharField(choices=[('1', 'session 1'), ('2', 'session 2')], max_length=40)),
                ('to_session', models.CharField(choices=[('1', 'session 1'), ('2', 'session 2')], max_length=40)),
                ('days', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=40)),
                ('status', models.BooleanField(choices=[(1, 'Accept'), (0, 'Reject')])),
                ('active_flag', models.BooleanField(default=True, verbose_name='active')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('apply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='employee.Employee')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('cc_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leavebalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('assign_leave_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leavetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('active_flag', models.BooleanField(default=True, verbose_name='active')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leavetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.Leavetype'),
        ),
        migrations.AddField(
            model_name='leaveapply',
            name='leavetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.Leavetype'),
        ),
    ]
