# Generated by Django 2.1.7 on 2019-11-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapply',
            name='apply_to',
            field=models.CharField(max_length=20),
        ),
    ]
