# Generated by Django 2.1.7 on 2019-11-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20191124_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapply',
            name='apply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='employee.Employee'),
        ),
    ]
