# Generated by Django 2.1.7 on 2019-11-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20191124_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapply',
            name='status',
            field=models.BooleanField(choices=[(1, 'Accept'), (0, 'Reject')], null=True),
        ),
    ]
