# Generated by Django 2.1.7 on 2019-11-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reporting_lead',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
