# Generated by Django 2.1.7 on 2019-11-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('LeaveType', models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Comp off', 'Comp off')], max_length=10)),
                ('Fromsession', models.CharField(choices=[('Session1', 'Session1'), ('Session2', 'Session2')], default='Session1', max_length=50)),
                ('Tosession', models.CharField(choices=[('Session1', 'Session1'), ('Session2', 'Session2')], default='Session1', max_length=50)),
                ('Days', models.CharField(default=' ', max_length=10)),
                ('Balance_days', models.CharField(default=' ', max_length=10)),
                ('ApplyTo', models.EmailField(choices=[('Manager', 'Manager'), ('Hr', 'Hr'), ('Admin', 'Admin')], default='', max_length=70)),
                ('CcTo', models.EmailField(default='', max_length=254)),
                ('Contact', models.CharField(default='', max_length=10)),
                ('Reason', models.TextField(max_length=500)),
                ('Status', models.BooleanField(default=None, null=True)),
                ('Attachment', models.FileField(default='', upload_to='media/')),
            ],
        ),
    ]
