# Generated by Django 2.1.7 on 2019-11-19 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import salary.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), salary.models.max_value_current_year])),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March '), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October '), ('Nov', 'November'), ('Dec', 'December')], max_length=30)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('esi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('earning', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active_flag', models.BooleanField(default=True, verbose_name='active')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_id', to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Salarydetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_to_company', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('esi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_basic_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_hra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_special_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_pf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_esi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active_flag', models.BooleanField(default=True, verbose_name='active')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_id', to='employee.Employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
